function mysqlVarcharLen(colName) {
  const n = String(colName || "").toLowerCase();
  if (/phone|tel|mobile/.test(n)) return 32;
  if (/email/.test(n)) return 255;
  if (/url|website|logo|link|path/.test(n)) return 512;
  if (/account|card|iban|inn|kpp|bic|swift/.test(n)) return 64;
  if (/code|status|type|slug/.test(n)) return 64;
  return 255;
}

function mapSqlCodeOnly(sql, mapper) {
  let out = "";
  let buf = "";
  let inSingle = false, inDouble = false, inTick = false, inLine = false, inBlock = false;
  const flushCode = () => { if (buf) { out += mapper(buf); buf = ""; } };
  for (let i = 0; i < sql.length; i++) {
    const c = sql[i], n = sql[i + 1];
    if (inLine) {
      out += c;
      if (c === "\n") inLine = false;
      continue;
    }
    if (inBlock) {
      out += c;
      if (c === "*" && n === "/") { out += "/"; i++; inBlock = false; }
      continue;
    }
    if (inSingle) {
      buf += c;
      if (c === "'" && n === "'") { buf += n; i++; }
      else if (c === "'") inSingle = false;
      continue;
    }
    if (inDouble) {
      buf += c;
      if (c === '"') inDouble = false;
      continue;
    }
    if (inTick) {
      buf += c;
      if (c === "`") inTick = false;
      continue;
    }
    if (c === "-" && n === "-") {
      flushCode();
      out += c;
      inLine = true;
      continue;
    }
    if (c === "/" && n === "*") {
      flushCode();
      out += c;
      inBlock = true;
      continue;
    }
    if (c === "'") { inSingle = true; buf += c; continue; }
    if (c === '"') { inDouble = true; buf += c; continue; }
    if (c === "`") { inTick = true; buf += c; continue; }
    buf += c;
  }
  flushCode();
  return out;
}

function mapMysqlCode(chunk) {
  let out = chunk;
  out = out.replace(/\bBOOLEAN\b/gi, "TINYINT(1)");
  out = out.replace(/\bTIMESTAMPTZ\b/gi, "DATETIME");
  out = out.replace(/\bUUID\b/gi, "CHAR(36)");
  out = out.replace(/\bBIGSERIAL\b/gi, "BIGINT AUTO_INCREMENT");
  out = out.replace(/\bSERIAL\b/gi, "INT AUTO_INCREMENT");
  out = out.replace(/\b(\w+)\s+VARCHAR(?!\s*\()/gi, (_, col) => `${col} VARCHAR(${mysqlVarcharLen(col)})`);
  out = out.replace(/\bVARCHAR(?!\s*\()/gi, "VARCHAR(255)");
  out = out.replace(/\b(\w+)\s+INT\s+PRIMARY\s+KEY\b/gi, (m, col) => {
    if (!/^id$/i.test(col) || /AUTO_INCREMENT/i.test(m)) return m;
    return `${col} INT AUTO_INCREMENT PRIMARY KEY`;
  });
  return out;
}

function dialectTypeHeader(dialect) {
  const d = String(dialect || "").toLowerCase();
  if (d === "mysql" || d === "mariadb") {
    return "-- Типы (применены на бэкенде): BOOLEAN→TINYINT(1), VARCHAR без длины→VARCHAR(n), SERIAL→AUTO_INCREMENT, TIMESTAMPTZ→DATETIME, UUID→CHAR(36)";
  }
  if (d === "mssql" || d === "sqlserver") {
    return "-- Типы (применены на бэкенде): BOOLEAN→BIT, SERIAL→INT IDENTITY(1,1), TIMESTAMPTZ→DATETIME2";
  }
  if (d === "oracle") {
    return "-- Типы (применены на бэкенде): BOOLEAN→NUMBER(1), VARCHAR→VARCHAR2(255), SERIAL→IDENTITY";
  }
  return "";
}

function stripModelTypeBanners(sql) {
  return String(sql || "").replace(/^[ \t]*--[ \t]*Типы данных:[^\n]*\n/i, "");
}

function sanitizeTargetDialectSql(sql, dialect) {
  const d = String(dialect || "").toLowerCase();
  if (!sql) return sql;
  let body = stripModelTypeBanners(sql);
  if (d === "mysql" || d === "mariadb") body = mapSqlCodeOnly(body, mapMysqlCode);
  else if (d === "mssql" || d === "sqlserver") {
    body = mapSqlCodeOnly(body, (c) => c.replace(/\bBOOLEAN\b/gi, "BIT").replace(/\bSERIAL\b/gi, "INT IDENTITY(1,1)").replace(/\bTIMESTAMPTZ\b/gi, "DATETIME2"));
  } else if (d === "oracle") {
    body = mapSqlCodeOnly(body, (c) => c
      .replace(/\bBOOLEAN\b/gi, "NUMBER(1)")
      .replace(/\bVARCHAR(?!\s*\()(?!2)/gi, "VARCHAR2(255)")
      .replace(/\bSERIAL\b/gi, "NUMBER GENERATED BY DEFAULT AS IDENTITY"));
  }
  const header = dialectTypeHeader(d);
  if (header && !body.includes(header)) body = header + "\n" + body.replace(/^\s+/, "");
  return body;
}

function parseOnDelete(line) {
  const m = String(line || "").match(/ON\s+DELETE\s+(CASCADE|RESTRICT|SET\s+NULL|SET\s+DEFAULT|NO\s+ACTION)/i);
  if (!m) return "NO ACTION";
  return m[1].replace(/\s+/g, " ").toUpperCase();
}

/** Тип колонки с поддержкой DECIMAL(10, 2) / VARCHAR(255) / DOUBLE PRECISION. */
function extractColumnMeta(line) {
  const raw = String(line || "").trim();
  const m = raw.match(/^["'`]?(\w+)["'`]?\s+(.+)$/i);
  if (!m || /^(PRIMARY|FOREIGN|CONSTRAINT|UNIQUE|CHECK|INDEX)$/i.test(m[1])) return null;
  const col = m[1].toLowerCase();
  let rest = m[2].trim();
  const stop = rest.search(/\b(NOT\s+NULL|NULL|DEFAULT|PRIMARY|UNIQUE|CHECK|REFERENCES|COLLATE|GENERATED|CONSTRAINT|AUTO_INCREMENT|IDENTITY)\b/i);
  let type = (stop >= 0 ? rest.slice(0, stop) : rest).trim().replace(/,\s*$/, "").trim();
  if (!type) return null;
  type = type.replace(/\s+/g, " ").toUpperCase();
  return {
    col,
    type,
    notNull: /\bNOT\s+NULL\b/i.test(rest),
    unique: /\bUNIQUE\b/i.test(rest),
    check: (/CHECK\s*\(/i.test(rest) && rest.match(/CHECK\s*\((.+)\)/i)) ? rest.match(/CHECK\s*\((.+)\)/i)[1] : null,
    fk: /\bREFERENCES\b/i.test(rest),
  };
}

function parseDdlTables(ddl) {
  const result = {};
  const tableRe = /CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?(?:["'`]?[\w]+["'`]?\.)?["'`]?(\w+)["'`]?\s*\(([\s\S]*?)\)\s*;/gi;
  let m;
  while ((m = tableRe.exec(ddl || ""))) {
    const tableName = m[1].toLowerCase();
    const cols = {};
    const fks = [];
    const checks = [];
    const uniques = [];
    const lines = m[2].split(/,(?![^(]*\))/).map(l => l.trim()).filter(Boolean);
    lines.forEach(line => {
      if (/^(CONSTRAINT\s+\w+\s+)?CHECK\s*\(/i.test(line)) {
        checks.push(line);
        return;
      }
      if (/^(CONSTRAINT\s+\w+\s+)?UNIQUE\s*\(/i.test(line)) {
        uniques.push(line);
        return;
      }
      const fkInline = line.match(/^["'`]?(\w+)["'`]?\s+[\w().,\s]+[\s\S]*?\bREFERENCES\s+["'`]?(\w+)["'`]?\s*(?:\(\s*["'`]?(\w+)["'`]?\s*\))?/i);
      const fkTable = line.match(/\bFOREIGN\s+KEY\s*\(\s*["'`]?(\w+)["'`]?\s*\)\s*REFERENCES\s+["'`]?(\w+)["'`]?\s*(?:\(\s*["'`]?(\w+)["'`]?\s*\))?/i);
      if (fkInline && !/^(PRIMARY|FOREIGN|CONSTRAINT|UNIQUE|CHECK|INDEX)$/i.test(fkInline[1])) {
        fks.push({ col: fkInline[1].toLowerCase(), parent: fkInline[2].toLowerCase(), parentCol: (fkInline[3] || "id").toLowerCase(), onDelete: parseOnDelete(line) });
      } else if (fkTable) {
        fks.push({ col: fkTable[1].toLowerCase(), parent: fkTable[2].toLowerCase(), parentCol: (fkTable[3] || "id").toLowerCase(), onDelete: parseOnDelete(line) });
      }
      const meta = extractColumnMeta(line);
      if (meta) {
        cols[meta.col] = {
          type: meta.type,
          notNull: meta.notNull,
          unique: meta.unique,
          check: meta.check,
          fk: meta.fk,
        };
      }
    });
    result[tableName] = { cols, fks, checks, uniques };
  }
  return result;
}

/** Имена таблиц даже из обрезанного DDL (без закрывающего ); ). */
function extractTableNames(ddl) {
  const names = new Set();
  // Не требуем кавычку ПОСЛЕ имени — иначе CREATE TABLE hotel ( не матчится.
  const re = /CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?(?:(?:"[^"]+"|[\w]+)\.)?(?:"([^"]+)"|([\w]+))/gi;
  let m;
  while ((m = re.exec(ddl || ""))) {
    const name = m[1] || m[2];
    if (name) names.add(name.toLowerCase());
  }
  return names;
}

function buildSchemaDiff(oldDdl, newDdl) {
  const oldT = parseDdlTables(oldDdl);
  const newT = parseDdlTables(newDdl);
  // Если схема обрезана посередине CREATE TABLE, parseDdlTables таблицу не видит,
  // а имя уже есть — иначе diff ошибочно требует CREATE заново.
  const oldNames = extractTableNames(oldDdl);
  const newNames = extractTableNames(newDdl);
  for (const t of Object.keys(oldT)) oldNames.add(t);
  for (const t of Object.keys(newT)) newNames.add(t);
  const addedCols = [];
  const addedTables = [];
  const droppedTables = [];
  const addedFks = [];
  for (const t of Object.keys(newT)) {
    if (!oldNames.has(t)) {
      addedTables.push(t);
      (newT[t].fks || []).forEach(fk => addedFks.push({ child: t, ...fk }));
      continue;
    }
    // Таблица есть в OLD по имени, но тело не распарсилось (обрезка) — не CREATE и не угадываем ALTER.
    if (!oldT[t]) continue;
    const oldCols = oldT[t].cols || oldT[t];
    const newCols = newT[t].cols || newT[t];
    for (const c of Object.keys(newCols)) {
      if (!oldCols[c]) addedCols.push({ table: t, col: c, type: newCols[c].type, notNull: newCols[c].notNull });
    }
    const oldFkKeys = new Set((oldT[t].fks || []).map(f => f.col + ">" + f.parent));
    (newT[t].fks || []).forEach(fk => {
      if (!oldFkKeys.has(fk.col + ">" + fk.parent)) addedFks.push({ child: t, ...fk });
    });
  }
  for (const t of oldNames) {
    if (!newNames.has(t)) droppedTables.push(t);
  }
  const lines = [];
  addedTables.forEach(t => lines.push(`CREATE TABLE ${t}`));
  addedCols.forEach(a => lines.push(`ALTER TABLE ${a.table} ADD COLUMN ${a.col} ${a.type}${a.notNull ? " NOT NULL" : ""}`));
  addedFks.forEach(f => lines.push(`FK ${f.child}.${f.col} → ${f.parent}(${f.parentCol})`));
  droppedTables.forEach(t => lines.push(`DROP TABLE ${t}`));
  return { addedCols, addedTables, droppedTables, addedFks, text: lines.join("\n") || "(явных отличий парсер не нашёл — всё равно сверь DDL построчно)" };
}

function identRe(name) {
  const n = String(name || "").replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  return "(?:[\"'`]?)" + n + "(?:[\"'`]?)";
}

function sqlHasAlterColumn(sql, table, col) {
  const re = new RegExp(
    "alter\\s+table\\s+(?:[\\w.]+\\.)?" + identRe(table) + "\\s+[\\s\\S]{0,600}?\\b" + String(col).replace(/[.*+?^${}()|[\]\\]/g, "\\$&") + "\\b",
    "i"
  );
  return re.test(sql || "");
}

function sqlHasFkReference(sql, child, parent, col) {
  const re = new RegExp(
    identRe(child) + "[\\s\\S]{0,2000}(?:foreign\\s+key\\s*\\(\\s*" + identRe(col) + "\\s*\\)|\\b" + String(col).replace(/[.*+?^${}()|[\]\\]/g, "\\$&") + "\\b[\\s\\S]{0,120})\\s*references\\s+" + identRe(parent),
    "i"
  );
  return re.test(sql || "");
}

function sqlHasCreateTable(sql, table) {
  return new RegExp("create\\s+table\\s+(?:if\\s+not\\s+exists\\s+)?" + identRe(table) + "\\b", "i").test(sql || "");
}

function ensureAltersFromDiff(sql, diff) {
  if (!sql || !diff || !diff.addedCols.length) return sql;
  const missing = diff.addedCols.filter(a => !sqlHasAlterColumn(sql, a.table, a.col));
  if (!missing.length) return sql;
  // Для существующих таблиц не вшиваем NOT NULL без DEFAULT — иначе падает на данных.
  const stmts = missing.map(a => {
    const type = a.type || "TEXT";
    return `ALTER TABLE ${a.table} ADD COLUMN ${a.col} ${type}; -- новое поле`;
  }).join("\n");
  if (/-- ШАГ 1:/i.test(sql)) return sql.replace(/(-- ШАГ 1:[^\n]*\n)/i, `$1${stmts}\n`);
  if (/COMMIT\s*;|ROLLBACK\s*;/i.test(sql)) return sql.replace(/\n(?=(COMMIT|ROLLBACK)\s*;)/i, "\n" + stmts + "\n");
  return sql + "\n" + stmts + "\n";
}

function ensureFksFromDiff(sql, diff) {
  if (!sql || !diff || !diff.addedFks || !diff.addedFks.length) return sql;
  const missing = diff.addedFks.filter(f => {
    // Уже есть FK в CREATE/ALTER (в т.ч. REFERENCES "Parent")
    if (sqlHasFkReference(sql, f.child, f.parent, f.col)) return false;
    return true;
  });
  if (!missing.length) return sql;
  const stmts = missing.map(f =>
    `ALTER TABLE ${f.child} ADD CONSTRAINT fk_${f.child}_${f.col} FOREIGN KEY (${f.col}) REFERENCES ${f.parent}(${f.parentCol || "id"}); -- FK`
  ).join("\n");
  if (/-- ШАГ 5:/i.test(sql)) return sql.replace(/(-- ШАГ 5:[^\n]*\n)/i, `$1${stmts}\n`);
  if (/COMMIT\s*;|ROLLBACK\s*;/i.test(sql)) return sql.replace(/\n(?=(COMMIT|ROLLBACK)\s*;)/i, "\n" + stmts + "\n");
  return sql + "\n" + stmts + "\n";
}

const PG_RESERVED = new Set([
  "user", "limit", "order", "group", "table", "check", "key", "offset", "select", "from", "where",
  "grant", "revoke", "session_user", "current_user", "authorization",
]);

function quoteIdentIfNeeded(name) {
  const raw = String(name || "").replace(/^["'`]+|["'`]+$/g, "");
  if (!raw) return name;
  if (PG_RESERVED.has(raw.toLowerCase()) || /[A-Z]/.test(raw)) return `"${raw}"`;
  return raw.toLowerCase();
}

function normIdent(name) {
  return String(name || "").replace(/^["'`]+|["'`]+$/g, "").toLowerCase();
}

/**
 * Пост-очистка сырого migration_sql: чинит типы, дубли, безымянные CONSTRAINT,
 * NOT NULL без DEFAULT на существующих таблицах, кавычки reserved.
 */
function cleanupMigrationSql(sql, opts) {
  if (!sql) return sql;
  const oldNames = new Set([...(opts && opts.oldTableNames ? opts.oldTableNames : [])].map(normIdent));
  let text = String(sql);

  // 1) Починить обрезанные DECIMAL/NUMERIC(n
  text = text.replace(/\b(DECIMAL|NUMERIC)\s*\(\s*(\d+)\s+(NOT\s+NULL|NULL|DEFAULT)/gi, "$1($2, 2) $3");
  text = text.replace(/\b(DECIMAL|NUMERIC)\s*\(\s*(\d+)\s*;/gi, "$1($2, 2);");

  // 2) ADD CONSTRAINT FOREIGN KEY → ADD CONSTRAINT fk_… FOREIGN KEY
  text = text.replace(
    /ALTER\s+TABLE\s+([^\s;]+)\s+ADD\s+CONSTRAINT\s+FOREIGN\s+KEY\s*\(\s*([^)]+?)\s*\)\s*REFERENCES\s+([^\s(;]+)\s*(?:\(([^)]*)\))?([^;]*);/gi,
    (_, table, cols, parent, pcol, rest) => {
      const t = normIdent(table);
      const c = normIdent(String(cols).split(",")[0]);
      const pname = `fk_${t}_${c}`.replace(/[^a-z0-9_]/gi, "_").slice(0, 60);
      const pref = pcol ? `(${pcol})` : "(id)";
      return `ALTER TABLE ${table} ADD CONSTRAINT ${pname} FOREIGN KEY (${cols}) REFERENCES ${parent}${pref}${rest || ""};`;
    }
  );

  // 3) Разбить на statements и вычистить дубли / опасный NOT NULL
  const parts = [];
  let buf = "";
  let inS = false, inD = false, inLine = false, inBlock = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i], n = text[i + 1];
    if (inLine) { buf += c; if (c === "\n") inLine = false; continue; }
    if (inBlock) { buf += c; if (c === "*" && n === "/") { buf += "/"; i++; inBlock = false; } continue; }
    if (inS) { buf += c; if (c === "'" && n === "'") { buf += "'"; i++; } else if (c === "'") inS = false; continue; }
    if (inD) { buf += c; if (c === '"') inD = false; continue; }
    if (c === "-" && n === "-") { buf += c; inLine = true; continue; }
    if (c === "/" && n === "*") { buf += c; inBlock = true; continue; }
    if (c === "'") { inS = true; buf += c; continue; }
    if (c === '"') { inD = true; buf += c; continue; }
    if (c === ";") { parts.push(buf.trim()); buf = ""; continue; }
    buf += c;
  }
  if (buf.trim()) parts.push(buf.trim());

  const createFkKeys = new Set();
  const createTables = new Set();
  parts.forEach(p => {
    const cm = p.match(/CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?["'`]?(\w+)["'`]?/i);
    if (cm) {
      createTables.add(cm[1].toLowerCase());
      const body = p.match(/\(([\s\S]*)\)\s*$/);
      if (body) {
        const re = /REFERENCES\s+["'`]?(\w+)["'`]/gi;
        let r;
        while ((r = re.exec(body[1]))) {
          const col = (body[1].slice(Math.max(0, r.index - 80), r.index).match(/["'`]?(\w+)["'`]?\s*$/) || [])[1];
          createFkKeys.add(cm[1].toLowerCase() + ">" + (col || "").toLowerCase() + ">" + r[1].toLowerCase());
          createFkKeys.add(cm[1].toLowerCase() + ">>" + r[1].toLowerCase());
        }
      }
    }
  });

  const seenAlterCol = new Set();
  const seenFkAlter = new Set();
  const out = [];

  for (let p of parts) {
    // убрать внутренние пометки генератора
    p = p.replace(/\s*--\s*причина:[^\n]*/gi, "");
    p = p.replace(/\s*--\s*новое поле[^\n]*/gi, "");
    p = p.replace(/\s*--\s*FK\s*$/gim, "");

    const alterCol = p.match(/^ALTER\s+TABLE\s+([^\s]+)\s+ADD\s+COLUMN\s+["'`]?(\w+)["'`]?\s+(.+)$/i);
    if (alterCol) {
      let tableTok = alterCol[1];
      const col = alterCol[2].toLowerCase();
      let rest = alterCol[3].trim().replace(/;?\s*$/, "");
      const tNorm = normIdent(tableTok);
      // единый стиль: если в скрипте есть CREATE "Card" — не плодим card
      const key = tNorm + "." + col;
      if (seenAlterCol.has(key)) continue;
      seenAlterCol.add(key);

      if (PG_RESERVED.has(tNorm) && !/^["`]/.test(tableTok)) tableTok = `"${tNorm}"`;

      // починить тип DECIMAL(10
      rest = rest.replace(/^(DECIMAL|NUMERIC)\s*\(\s*(\d+)\s*(?=\s+NOT\s+NULL|\s+NULL|\s+DEFAULT|$)/i, "$1($2, 2)");

      // существующая таблица + NOT NULL без DEFAULT → убрать NOT NULL (безопаснее для данных)
      const isExisting = oldNames.has(tNorm) || (!createTables.has(tNorm) && oldNames.size > 0);
      if (isExisting && /\bNOT\s+NULL\b/i.test(rest) && !/\bDEFAULT\b/i.test(rest)) {
        rest = rest.replace(/\bNOT\s+NULL\b/gi, "").replace(/\s{2,}/g, " ").trim();
      }

      out.push(`ALTER TABLE ${tableTok} ADD COLUMN ${col} ${rest}`);
      continue;
    }

    const alterFk = p.match(/^ALTER\s+TABLE\s+([^\s]+)\s+ADD\s+CONSTRAINT\s+(\w+)\s+FOREIGN\s+KEY\s*\(\s*([^)]+)\)\s*REFERENCES\s+([^\s(;]+)(?:\(([^)]*)\))?(.*)$/i);
    const alterFkAnon = p.match(/^ALTER\s+TABLE\s+([^\s]+)\s+ADD\s+(?:CONSTRAINT\s+)?FOREIGN\s+KEY/i);
    if (alterFk || alterFkAnon) {
      const tableTok = alterFk ? alterFk[1] : (p.match(/ALTER\s+TABLE\s+([^\s]+)/i) || [])[1];
      const tNorm = normIdent(tableTok);
      const cols = alterFk ? alterFk[3] : ((p.match(/FOREIGN\s+KEY\s*\(\s*([^)]+)\)/i) || [])[1] || "");
      const parent = alterFk ? alterFk[4] : ((p.match(/REFERENCES\s+([^\s(;]+)/i) || [])[1] || "");
      const col0 = normIdent(String(cols).split(",")[0]);
      const pNorm = normIdent(parent);
      const fkKey = tNorm + ">" + col0 + ">" + pNorm;

      // FK уже в CREATE этой (новой) таблицы — ALTER не нужен
      if (createTables.has(tNorm) && (createFkKeys.has(fkKey) || createFkKeys.has(tNorm + ">>" + pNorm))) continue;
      if (seenFkAlter.has(fkKey)) continue;
      seenFkAlter.add(fkKey);

      if (alterFk) {
        let stmt = p.replace(/;?\s*$/, "");
        if (PG_RESERVED.has(tNorm) && !/^["`]/.test(tableTok)) {
          stmt = stmt.replace(/ALTER\s+TABLE\s+[^\s]+/i, `ALTER TABLE "${tNorm}"`);
        }
        if (PG_RESERVED.has(pNorm) && parent && !/^["`]/.test(parent)) {
          stmt = stmt.replace(new RegExp("REFERENCES\\s+" + parent.replace(/[.*+?^${}()|[\]\\]/g, "\\$&") + "\\b", "i"), `REFERENCES "${pNorm}"`);
        }
        out.push(stmt);
      } else {
        // безымянный — уже должны были починить regex выше; если остался — дропаем как мусор
        continue;
      }
      continue;
    }

    out.push(p.replace(/;?\s*$/, ""));
  }

  // Собрать обратно, сохранив BEGIN/COMMIT структуру по возможности
  let body = out.map(s => /;\s*$/.test(s) ? s : s + ";").join("\n\n");
  if (!/^\s*BEGIN/i.test(body) && /^\s*BEGIN/i.test(text)) body = "BEGIN;\n\n" + body;
  if (!/\bCOMMIT\s*;|\bROLLBACK\s*;/i.test(body) && /\bCOMMIT\s*;/i.test(text)) body += "\n\nCOMMIT;";
  if (!/\bCOMMIT\s*;|\bROLLBACK\s*;/i.test(body) && /\bROLLBACK\s*;/i.test(text)) body += "\n\nROLLBACK;";
  return body.trim() + "\n";
}

function sqlCodeOnly(sql) {
  let code = "";
  mapSqlCodeOnly(sql || "", (c) => { code += c; return c; });
  return code;
}

function lintMigrationSql(sql, dialect) {
  const warnings = [];
  const d = String(dialect || "").toLowerCase();
  const code = sqlCodeOnly(sql);
  if (d === "mysql" || d === "mariadb") {
    if (/\bVARCHAR\s*(?!\s*\()/i.test(code)) warnings.push("MySQL: остался VARCHAR без длины");
  }
  if ((sql.match(/\bSTART\s+TRANSACTION\b|\bBEGIN\b/gi) || []).length && !/\bCOMMIT\b|\bROLLBACK\b/i.test(sql)) {
    warnings.push("Транзакция без COMMIT/ROLLBACK");
  }
  if (/\b(DECIMAL|NUMERIC)\s*\(\s*\d+\s+(NOT\s+NULL|NULL)/i.test(code)) {
    warnings.push("Обнаружен обрезанный DECIMAL/NUMERIC — проверьте типы колонок");
  }
  if (/ADD\s+CONSTRAINT\s+FOREIGN\s+KEY/i.test(code)) {
    warnings.push("ADD CONSTRAINT без имени ограничения");
  }
  return warnings;
}

function buildConstraintFacts(ddl, opts) {
  const compact = !!(opts && opts.compact);
  const tables = parseDdlTables(ddl);
  const lines = [];
  for (const [t, info] of Object.entries(tables)) {
    (info.fks || []).forEach(fk => {
      const action = fk.onDelete || "NO ACTION";
      const expect = action === "CASCADE"
        ? "удаление родителя УСПЕШНО, дочерние строки исчезают; ошибку НЕ ожидать"
        : (action === "SET NULL"
          ? "удаление родителя УСПЕШНО, дочерний FK становится NULL"
          : "удаление родителя должно УПАСТЬ с ошибкой FK (RESTRICT/NO ACTION)");
      lines.push(`FK ${t}.${fk.col} → ${fk.parent}(${fk.parentCol}) ON DELETE ${action} — ${expect}`);
    });
    const nn = [];
    Object.entries(info.cols || {}).forEach(([c, meta]) => {
      if (meta.notNull) nn.push(c);
      if (meta.unique) lines.push(`UNIQUE ${t}.${c} — дубликат должен упасть`);
      if (meta.check) lines.push(`CHECK ${t}.${c}: ${meta.check} — значение вне диапазона должно упасть`);
    });
    if (nn.length) {
      lines.push(compact
        ? `NOT NULL ${t}(${nn.join(", ")}) — достаточно ОДНОГО репрезентативного INSERT NULL, не отдельный тест на каждую колонку`
        : nn.map(c => `NOT NULL ${t}.${c} — INSERT NULL должен упасть`).join("\n"));
    }
    (info.checks || []).forEach(ch => lines.push(`CHECK ${t}: ${ch}`));
    (info.uniques || []).forEach(u => lines.push(`UNIQUE ${t}: ${u}`));
  }
  return lines.filter(Boolean).join("\n") || "(парсер не нашёл FK/CHECK/UNIQUE/NOT NULL — тестируй только то, что явно видно в DDL)";
}

function lintIntegritySql(sql) {
  const warnings = [];
  const text = String(sql || "");
  const blocks = text.split(/BEGIN\s*;/i).slice(1);
  blocks.forEach((block, i) => {
    const n = i + 1;
    const deletes = [...block.matchAll(/DELETE\s+FROM\s+["'`]?(\w+)["'`]?/gi)];
    deletes.forEach(d => {
      const table = d[1];
      const tail = block.slice(d.index || 0);
      const leak = new RegExp(
        "SELECT[\\s\\S]{0,500}?=\\s*\\(\\s*SELECT\\s+[\\w.*]+\\s+FROM\\s+[\"'`]?" + table + "\\b",
        "i"
      );
      if (leak.test(tail)) {
        warnings.push("Блок " + n + ": после DELETE FROM " + table + " проверка ищет строки через подзапрос к уже удалённой таблице. Считайте дочерние записи по их собственному id.");
      }
    });
    const delById = [...block.matchAll(/DELETE\s+FROM\s+["'`]?\w+["'`]?\s+WHERE\s+["'`]?id["'`]?\s*=\s*(\d+)/gi)];
    delById.forEach(d => {
      const parentId = d[1];
      const tail = block.slice(d.index || 0);
      const byFk = new RegExp("SELECT[\\s\\S]{0,400}WHERE\\s+[\"'`]?(?!id\\b)(\\w+)[\"'`]?\\s*=\\s*" + parentId + "\\b", "i");
      const byChildPk = /SELECT\s+COUNT\s*\(\s*\*\s*\)[\s\S]{0,200}WHERE\s+["'`]?id["'`]?\s*=\s*\d+/i.test(tail);
      if (byFk.test(tail) && !byChildPk) {
        warnings.push("Блок " + n + ": CASCADE проверяется по FK = " + parentId + ". Надёжнее COUNT(*) ... WHERE id = <id дочерней строки>.");
      }
    });
    const subParents = [...block.matchAll(/SELECT\s+id\s+FROM\s+["'`]?(\w+)["'`]?\s+WHERE/gi)].map(m => m[1].toLowerCase());
    subParents.forEach(parent => {
      const inserted = new RegExp("INSERT\\s+INTO\\s+[\"'`]?" + parent + "\\b", "i").test(block);
      if (!inserted) {
        warnings.push("Блок " + n + ": подзапрос к " + parent + " без INSERT этой таблицы в том же BEGIN — после ROLLBACK предыдущих тестов строк не будет.");
      }
    });
  });
  return [...new Set(warnings)];
}

const PG_RESERVED_IDENT = /^(user|order|group|table|limit|offset|check|key)$/i;

function quoteReservedTableIdents(sql, dialect) {
  if (!/postgres/i.test(String(dialect || ""))) return sql;
  return String(sql || "").replace(
    /\b((?:INSERT\s+INTO|DELETE\s+FROM|UPDATE|JOIN|FROM|TABLE))\s+(?!["'`])(User|Order|Group|Table|Limit|Offset|Check|Key|user|order|group|table|limit|offset|check|key)\b/g,
    (m, kw, ident) => kw + ' "' + ident + '"'
  );
}

function lintReservedIdents(sql, dialect) {
  if (!/postgres/i.test(String(dialect || ""))) return [];
  const warnings = [];
  const re = /\b(?:INSERT\s+INTO|DELETE\s+FROM|UPDATE|JOIN|FROM|TABLE)\s+(?!["'`])(User|Order|Group|Table|Limit|Offset|Check|Key)\b/gi;
  let m;
  while ((m = re.exec(sql || ""))) {
    warnings.push("Зарезервированное имя " + m[1] + " без кавычек — в PostgreSQL скрипт не выполнится. Нужно \"" + m[1] + "\".");
  }
  return [...new Set(warnings)];
}

function ddlTransactionalNote(dialect) {
  const d = String(dialect || "").toLowerCase();
  if (d === "postgresql" || d === "postgres") return "";
  return "-- ВНИМАНИЕ: в " + d + " DDL (CREATE/ALTER TABLE) обычно делает неявный COMMIT. ROLLBACK не откатит уже выполненные DDL. Не используйте этот скрипт как безопасный dry-run на проде.";
}

module.exports = {
  mysqlVarcharLen,
  sanitizeTargetDialectSql,
  parseDdlTables,
  extractColumnMeta,
  extractTableNames,
  buildSchemaDiff,
  ensureAltersFromDiff,
  ensureFksFromDiff,
  cleanupMigrationSql,
  lintMigrationSql,
  dialectTypeHeader,
  ddlTransactionalNote,
  parseOnDelete,
  buildConstraintFacts,
  lintIntegritySql,
  quoteReservedTableIdents,
  lintReservedIdents,
};
