function mysqlVarcharLen(colName) {
  const n = String(colName || "").toLowerCase();
  if (/phone|tel|mobile/.test(n)) return 32;
  if (/email/.test(n)) return 255;
  if (/url|website|logo|link|path/.test(n)) return 512;
  if (/account|card|iban|inn|kpp|bic|swift/.test(n)) return 64;
  if (/code|status|type|slug/.test(n)) return 64;
  return 255;
}

function mapSqlCodeOnly(sql, mapper) {
  let out = "";
  let buf = "";
  let inSingle = false, inDouble = false, inTick = false, inLine = false, inBlock = false;
  const flushCode = () => { if (buf) { out += mapper(buf); buf = ""; } };
  for (let i = 0; i < sql.length; i++) {
    const c = sql[i], n = sql[i + 1];
    if (inLine) {
      out += c;
      if (c === "\n") inLine = false;
      continue;
    }
    if (inBlock) {
      out += c;
      if (c === "*" && n === "/") { out += "/"; i++; inBlock = false; }
      continue;
    }
    if (inSingle) {
      buf += c;
      if (c === "'" && n === "'") { buf += n; i++; }
      else if (c === "'") inSingle = false;
      continue;
    }
    if (inDouble) {
      buf += c;
      if (c === '"') inDouble = false;
      continue;
    }
    if (inTick) {
      buf += c;
      if (c === "`") inTick = false;
      continue;
    }
    if (c === "-" && n === "-") {
      flushCode();
      out += c;
      inLine = true;
      continue;
    }
    if (c === "/" && n === "*") {
      flushCode();
      out += c;
      inBlock = true;
      continue;
    }
    if (c === "'") { inSingle = true; buf += c; continue; }
    if (c === '"') { inDouble = true; buf += c; continue; }
    if (c === "`") { inTick = true; buf += c; continue; }
    buf += c;
  }
  flushCode();
  return out;
}

function mapMysqlCode(chunk) {
  let out = chunk;
  out = out.replace(/\bBOOLEAN\b/gi, "TINYINT(1)");
  out = out.replace(/\bTIMESTAMPTZ\b/gi, "DATETIME");
  out = out.replace(/\bUUID\b/gi, "CHAR(36)");
  out = out.replace(/\bBIGSERIAL\b/gi, "BIGINT AUTO_INCREMENT");
  out = out.replace(/\bSERIAL\b/gi, "INT AUTO_INCREMENT");
  out = out.replace(/\b(\w+)\s+VARCHAR(?!\s*\()/gi, (_, col) => `${col} VARCHAR(${mysqlVarcharLen(col)})`);
  out = out.replace(/\bVARCHAR(?!\s*\()/gi, "VARCHAR(255)");
  out = out.replace(/\b(\w+)\s+INT\s+PRIMARY\s+KEY\b/gi, (m, col) => {
    if (!/^id$/i.test(col) || /AUTO_INCREMENT/i.test(m)) return m;
    return `${col} INT AUTO_INCREMENT PRIMARY KEY`;
  });
  return out;
}

function dialectTypeHeader(dialect) {
  const d = String(dialect || "").toLowerCase();
  if (d === "mysql" || d === "mariadb") {
    return "-- Типы (применены на бэкенде): BOOLEAN→TINYINT(1), VARCHAR без длины→VARCHAR(n), SERIAL→AUTO_INCREMENT, TIMESTAMPTZ→DATETIME, UUID→CHAR(36)";
  }
  if (d === "mssql" || d === "sqlserver") {
    return "-- Типы (применены на бэкенде): BOOLEAN→BIT, SERIAL→INT IDENTITY(1,1), TIMESTAMPTZ→DATETIME2";
  }
  if (d === "oracle") {
    return "-- Типы (применены на бэкенде): BOOLEAN→NUMBER(1), VARCHAR→VARCHAR2(255), SERIAL→IDENTITY";
  }
  return "";
}

function stripModelTypeBanners(sql) {
  return String(sql || "").replace(/^[ \t]*--[ \t]*Типы данных:[^\n]*\n/i, "");
}

function sanitizeTargetDialectSql(sql, dialect) {
  const d = String(dialect || "").toLowerCase();
  if (!sql) return sql;
  let body = stripModelTypeBanners(sql);
  if (d === "mysql" || d === "mariadb") body = mapSqlCodeOnly(body, mapMysqlCode);
  else if (d === "mssql" || d === "sqlserver") {
    body = mapSqlCodeOnly(body, (c) => c.replace(/\bBOOLEAN\b/gi, "BIT").replace(/\bSERIAL\b/gi, "INT IDENTITY(1,1)").replace(/\bTIMESTAMPTZ\b/gi, "DATETIME2"));
  } else if (d === "oracle") {
    body = mapSqlCodeOnly(body, (c) => c
      .replace(/\bBOOLEAN\b/gi, "NUMBER(1)")
      .replace(/\bVARCHAR(?!\s*\()(?!2)/gi, "VARCHAR2(255)")
      .replace(/\bSERIAL\b/gi, "NUMBER GENERATED BY DEFAULT AS IDENTITY"));
  }
  const header = dialectTypeHeader(d);
  if (header && !body.includes(header)) body = header + "\n" + body.replace(/^\s+/, "");
  return body;
}

function parseOnDelete(line) {
  const m = String(line || "").match(/ON\s+DELETE\s+(CASCADE|RESTRICT|SET\s+NULL|SET\s+DEFAULT|NO\s+ACTION)/i);
  if (!m) return "NO ACTION";
  return m[1].replace(/\s+/g, " ").toUpperCase();
}

/** Тип колонки с поддержкой DECIMAL(10, 2) / VARCHAR(255) / DOUBLE PRECISION. */
function extractColumnMeta(line) {
  const raw = String(line || "").trim();
  const m = raw.match(/^["'`]?(\w+)["'`]?\s+(.+)$/i);
  if (!m || /^(PRIMARY|FOREIGN|CONSTRAINT|UNIQUE|CHECK|INDEX)$/i.test(m[1])) return null;
  const col = m[1].toLowerCase();
  let rest = m[2].trim();
  const stop = rest.search(/\b(NOT\s+NULL|NULL|DEFAULT|PRIMARY|UNIQUE|CHECK|REFERENCES|COLLATE|GENERATED|CONSTRAINT|AUTO_INCREMENT|IDENTITY)\b/i);
  let type = (stop >= 0 ? rest.slice(0, stop) : rest).trim().replace(/,\s*$/, "").trim();
  if (!type) return null;
  type = type.replace(/\s+/g, " ").toUpperCase();
  return {
    col,
    type,
    notNull: /\bNOT\s+NULL\b/i.test(rest),
    unique: /\bUNIQUE\b/i.test(rest),
    check: (/CHECK\s*\(/i.test(rest) && rest.match(/CHECK\s*\((.+)\)/i)) ? rest.match(/CHECK\s*\((.+)\)/i)[1] : null,
    fk: /\bREFERENCES\b/i.test(rest),
  };
}

function parseDdlTables(ddl) {
  const result = {};
  const tableRe = /CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?(?:["'`]?[\w]+["'`]?\.)?["'`]?(\w+)["'`]?\s*\(([\s\S]*?)\)\s*;/gi;
  let m;
  while ((m = tableRe.exec(ddl || ""))) {
    const tableName = m[1].toLowerCase();
    const cols = {};
    const fks = [];
    const checks = [];
    const uniques = [];
    const lines = m[2].split(/,(?![^(]*\))/).map(l => l.trim()).filter(Boolean);
    lines.forEach(line => {
      if (/^(CONSTRAINT\s+\w+\s+)?CHECK\s*\(/i.test(line)) {
        checks.push(line);
        return;
      }
      if (/^(CONSTRAINT\s+\w+\s+)?UNIQUE\s*\(/i.test(line)) {
        uniques.push(line);
        return;
      }
      const fkInline = line.match(/^["'`]?(\w+)["'`]?\s+[\w().,\s]+[\s\S]*?\bREFERENCES\s+["'`]?(\w+)["'`]?\s*(?:\(\s*["'`]?(\w+)["'`]?\s*\))?/i);
      const fkTable = line.match(/\bFOREIGN\s+KEY\s*\(\s*["'`]?(\w+)["'`]?\s*\)\s*REFERENCES\s+["'`]?(\w+)["'`]?\s*(?:\(\s*["'`]?(\w+)["'`]?\s*\))?/i);
      if (fkInline && !/^(PRIMARY|FOREIGN|CONSTRAINT|UNIQUE|CHECK|INDEX)$/i.test(fkInline[1])) {
        fks.push({ col: fkInline[1].toLowerCase(), parent: fkInline[2].toLowerCase(), parentCol: (fkInline[3] || "id").toLowerCase(), onDelete: parseOnDelete(line) });
      } else if (fkTable) {
        fks.push({ col: fkTable[1].toLowerCase(), parent: fkTable[2].toLowerCase(), parentCol: (fkTable[3] || "id").toLowerCase(), onDelete: parseOnDelete(line) });
      }
      const meta = extractColumnMeta(line);
      if (meta) {
        cols[meta.col] = {
          type: meta.type,
          notNull: meta.notNull,
          unique: meta.unique,
          check: meta.check,
          fk: meta.fk,
        };
      }
    });
    result[tableName] = { cols, fks, checks, uniques };
  }
  return result;
}

/** Имена таблиц даже из обрезанного DDL (без закрывающего ); ). */
function extractTableNames(ddl) {
  const names = new Set();
  // Не требуем кавычку ПОСЛЕ имени — иначе CREATE TABLE hotel ( не матчится.
  const re = /CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?(?:(?:"[^"]+"|[\w]+)\.)?(?:"([^"]+)"|([\w]+))/gi;
  let m;
  while ((m = re.exec(ddl || ""))) {
    const name = m[1] || m[2];
    if (name) names.add(name.toLowerCase());
  }
  return names;
}

function inferParentTableFromCol(col, knownTables) {
  const m = String(col || "").toLowerCase().match(/^([a-z][a-z0-9_]*)_id$/);
  if (!m) return null;
  const base = m[1];
  if (knownTables.has(base)) return base;
  return null;
}

function buildSchemaDiff(oldDdl, newDdl) {
  const oldT = parseDdlTables(oldDdl);
  const newT = parseDdlTables(newDdl);
  // Если схема обрезана посередине CREATE TABLE, parseDdlTables таблицу не видит,
  // а имя уже есть — иначе diff ошибочно требует CREATE заново.
  const oldNames = extractTableNames(oldDdl);
  const newNames = extractTableNames(newDdl);
  for (const t of Object.keys(oldT)) oldNames.add(t);
  for (const t of Object.keys(newT)) newNames.add(t);
  const knownTables = new Set([...oldNames, ...newNames]);
  const addedCols = [];
  const addedTables = [];
  const droppedTables = [];
  const addedFks = [];
  for (const t of Object.keys(newT)) {
    if (!oldNames.has(t)) {
      addedTables.push(t);
      (newT[t].fks || []).forEach(fk => addedFks.push({ child: t, ...fk }));
      continue;
    }
    // Таблица есть в OLD по имени, но тело не распарсилось (обрезка) — не CREATE и не угадываем ALTER.
    if (!oldT[t]) continue;
    const oldCols = oldT[t].cols || oldT[t];
    const newCols = newT[t].cols || newT[t];
    for (const c of Object.keys(newCols)) {
      if (!oldCols[c]) addedCols.push({ table: t, col: c, type: newCols[c].type, notNull: newCols[c].notNull });
    }
    const oldFkKeys = new Set((oldT[t].fks || []).map(f => f.col + ">" + f.parent));
    (newT[t].fks || []).forEach(fk => {
      if (!oldFkKeys.has(fk.col + ">" + fk.parent)) addedFks.push({ child: t, ...fk });
    });
  }
  // NEW DDL часто пишет account_id INT без REFERENCES — выводим FK по имени колонки,
  // если родительская таблица есть в схеме (account_id → account).
  const fkSeen = new Set(addedFks.map(f => `${f.child}>${f.col}>${f.parent}`));
  addedCols.forEach(a => {
    const parent = inferParentTableFromCol(a.col, knownTables);
    if (!parent || parent === a.table) return;
    const key = `${a.table}>${a.col}>${parent}`;
    if (fkSeen.has(key)) return;
    const oldFkKeys = new Set(((oldT[a.table] || {}).fks || []).map(f => f.col + ">" + f.parent));
    if (oldFkKeys.has(a.col + ">" + parent)) return;
    fkSeen.add(key);
    // ON DELETE как у других FK на того же родителя в NEW, иначе без действия
    let onDelete = "NO ACTION";
    for (const info of Object.values(newT)) {
      const hit = (info.fks || []).find(f => f.parent === parent && f.onDelete && f.onDelete !== "NO ACTION");
      if (hit) { onDelete = hit.onDelete; break; }
    }
    addedFks.push({ child: a.table, col: a.col, parent, parentCol: "id", onDelete, inferred: true });
  });
  for (const t of oldNames) {
    if (!newNames.has(t)) droppedTables.push(t);
  }
  const lines = [];
  addedTables.forEach(t => lines.push(`CREATE TABLE ${t}`));
  addedCols.forEach(a => lines.push(`ALTER TABLE ${a.table} ADD COLUMN ${a.col} ${a.type}${a.notNull ? " NOT NULL" : ""}`));
  addedFks.forEach(f => lines.push(`FK ${f.child}.${f.col} → ${f.parent}(${f.parentCol})${f.inferred ? " (inferred)" : ""}`));
  droppedTables.forEach(t => lines.push(`DROP TABLE ${t}`));
  return { addedCols, addedTables, droppedTables, addedFks, text: lines.join("\n") || "(явных отличий парсер не нашёл — всё равно сверь DDL построчно)" };
}

function identRe(name) {
  const n = String(name || "").replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  return "(?:[\"'`]?)" + n + "(?:[\"'`]?)";
}

function sqlHasAlterColumn(sql, table, col) {
  const re = new RegExp(
    "alter\\s+table\\s+(?:[\\w.]+\\.)?" + identRe(table) + "\\s+[\\s\\S]{0,600}?\\b" + String(col).replace(/[.*+?^${}()|[\]\\]/g, "\\$&") + "\\b",
    "i"
  );
  return re.test(sql || "");
}

function sqlHasFkReference(sql, child, parent, col) {
  const re = new RegExp(
    identRe(child) + "[\\s\\S]{0,2000}(?:foreign\\s+key\\s*\\(\\s*" + identRe(col) + "\\s*\\)|\\b" + String(col).replace(/[.*+?^${}()|[\]\\]/g, "\\$&") + "\\b[\\s\\S]{0,120})\\s*references\\s+" + identRe(parent),
    "i"
  );
  return re.test(sql || "");
}

function sqlHasCreateTable(sql, table) {
  return new RegExp("create\\s+table\\s+(?:if\\s+not\\s+exists\\s+)?" + identRe(table) + "\\b", "i").test(sql || "");
}

function ensureAltersFromDiff(sql, diff) {
  if (!sql || !diff || !diff.addedCols.length) return sql;
  const missing = diff.addedCols.filter(a => !sqlHasAlterColumn(sql, a.table, a.col));
  if (!missing.length) return sql;
  // Для существующих таблиц не вшиваем NOT NULL без DEFAULT — иначе падает на данных.
  const stmts = missing.map(a => {
    const type = a.type || "TEXT";
    return `ALTER TABLE ${a.table} ADD COLUMN ${a.col} ${type}; -- новое поле`;
  }).join("\n");
  if (/-- ШАГ 1:/i.test(sql)) return sql.replace(/(-- ШАГ 1:[^\n]*\n)/i, `$1${stmts}\n`);
  if (/COMMIT\s*;|ROLLBACK\s*;/i.test(sql)) return sql.replace(/\n(?=(COMMIT|ROLLBACK)\s*;)/i, "\n" + stmts + "\n");
  return sql + "\n" + stmts + "\n";
}

function ensureFksFromDiff(sql, diff) {
  if (!sql || !diff || !diff.addedFks || !diff.addedFks.length) return sql;
  const missing = diff.addedFks.filter(f => {
    // Уже есть FK в CREATE/ALTER (в т.ч. REFERENCES "Parent")
    if (sqlHasFkReference(sql, f.child, f.parent, f.col)) return false;
    return true;
  });
  if (!missing.length) return sql;
  const stmts = missing.map(f => {
    const child = quoteIdentIfNeeded(f.child);
    const parent = quoteIdentIfNeeded(f.parent);
    const onDel = f.onDelete && f.onDelete !== "NO ACTION" ? ` ON DELETE ${f.onDelete}` : "";
    return `ALTER TABLE ${child} ADD CONSTRAINT fk_${normIdent(f.child)}_${normIdent(f.col)} FOREIGN KEY (${f.col}) REFERENCES ${parent}(${f.parentCol || "id"})${onDel};`;
  }).join("\n");
  if (/-- ШАГ 5:/i.test(sql)) return sql.replace(/(-- ШАГ 5:[^\n]*\n)/i, `$1${stmts}\n`);
  if (/COMMIT\s*;|ROLLBACK\s*;/i.test(sql)) return sql.replace(/\n(?=(COMMIT|ROLLBACK)\s*;)/i, "\n" + stmts + "\n");
  return sql + "\n" + stmts + "\n";
}

const PG_RESERVED = new Set([
  "user", "limit", "order", "group", "table", "check", "key", "offset", "select", "from", "where",
  "grant", "revoke", "session_user", "current_user", "authorization",
]);

function quoteIdentIfNeeded(name) {
  const raw = String(name || "").replace(/^["'`]+|["'`]+$/g, "");
  if (!raw) return name;
  if (PG_RESERVED.has(raw.toLowerCase()) || /[A-Z]/.test(raw)) return `"${raw}"`;
  return raw.toLowerCase();
}

function normIdent(name) {
  return String(name || "").replace(/^["'`]+|["'`]+$/g, "").toLowerCase();
}

/** Имена колонок из SELECT-списка (пропускаем литералы и выражения с скобками). */
function bareSelectColumnNames(selectExpr) {
  const cols = [];
  let depth = 0, cur = "";
  const s = String(selectExpr || "");
  for (let i = 0; i < s.length; i++) {
    const c = s[i];
    if (c === "(") { depth++; cur += c; continue; }
    if (c === ")") { depth = Math.max(0, depth - 1); cur += c; continue; }
    if (c === "," && depth === 0) {
      cols.push(cur.trim());
      cur = "";
      continue;
    }
    cur += c;
  }
  if (cur.trim()) cols.push(cur.trim());
  const names = [];
  cols.forEach(raw => {
    let t = raw.replace(/\s+AS\s+["'`]?\w+["'`]?\s*$/i, "").trim();
    if (/^null$/i.test(t) || /^true$/i.test(t) || /^false$/i.test(t)) return;
    if (/^[\d.]+$/.test(t) || /^'/.test(t) || /^\$/.test(t)) return;
    if (/\(|\)/.test(t) || /^CURRENT_/i.test(t) || /^NEXTVAL\b/i.test(t)) return;
    const m = t.match(/^(?:["'`]?\w+["'`]?\.)?["'`]?(\w+)["'`]?$/i);
    if (m) names.push(m[1].toLowerCase());
  });
  return names;
}

/**
 * INSERT…SELECT валиден, если все «голые» колонки SELECT есть у FROM-таблицы в OLD (или NEW).
 * null = не удалось разобрать / нет схемы — не трогаем.
 */
function validateInsertSelectAgainstSchema(stmt, oldTables, newTables) {
  const code = String(stmt || "").replace(/^(?:\s*--[^\n]*\n)+/, "").trim();
  const m = code.match(
    /^INSERT\s+INTO\s+("[^"]+"|\w+)\s*(?:\(([^)]*)\))?\s*SELECT\s+([\s\S]+?)\s+FROM\s+("[^"]+"|\w+)/i
  );
  if (!m) return { ok: true, skipped: false };
  const from = normIdent(m[4]);
  const selectCols = bareSelectColumnNames(m[3]);
  if (!selectCols.length) return { ok: true, skipped: false };
  const info = (oldTables && oldTables[from]) || (newTables && newTables[from]);
  if (!info || !info.cols) {
    // Есть OLD-схема, но таблицы-источника в ней нет и это не новая CREATE — подозрительно
    if (oldTables && Object.keys(oldTables).length && !(newTables && newTables[from])) {
      return { ok: false, skipped: true, from, missing: selectCols, reason: "source_table_unknown" };
    }
    return { ok: true, skipped: false };
  }
  const known = new Set(Object.keys(info.cols));
  const missing = selectCols.filter(c => !known.has(c));
  if (missing.length) return { ok: false, skipped: true, from, missing, reason: "missing_columns" };
  return { ok: true, skipped: false };
}

/** Все ADD CONSTRAINT FK и CREATE INDEX — в ШАГ 5 (после backfill). */
function relocateFksAndIndexesToStep5(statements) {
  const fks = [];
  const idxs = [];
  const rest = [];
  const seenFk = new Set();
  const seenIdx = new Set();
  statements.forEach(s => {
    const code = String(s || "").replace(/^(?:\s*--[^\n]*\n)+/, "").trim();
    if (/^ALTER\s+TABLE\s+\S+\s+ADD\s+CONSTRAINT\s+\w+\s+FOREIGN\s+KEY/i.test(code)) {
      const key = code.replace(/\s+/g, " ").toLowerCase();
      if (!seenFk.has(key)) { seenFk.add(key); fks.push(code); }
      return;
    }
    if (/^CREATE\s+(?:UNIQUE\s+)?INDEX\b/i.test(code)) {
      const key = code.replace(/\s+/g, " ").toLowerCase();
      if (!seenIdx.has(key)) { seenIdx.add(key); idxs.push(code); }
      return;
    }
    rest.push(s);
  });
  if (!fks.length && !idxs.length) return statements;
  // Перед COMMIT/ROLLBACK; если есть отдельный комментарий ШАГ 5 — сразу после него
  let insertAt = rest.findIndex(s => /\b(COMMIT|ROLLBACK)\b/i.test(String(s)));
  if (insertAt < 0) insertAt = rest.length;
  const step5Only = rest.findIndex((s, i) =>
    i < insertAt && /--\s*ШАГ\s*5:/i.test(String(s)) && !/\b(COMMIT|ROLLBACK)\b/i.test(String(s))
  );
  if (step5Only >= 0) insertAt = step5Only + 1;
  rest.splice(insertAt, 0, ...fks, ...idxs);
  return rest;
}

/**
 * Пост-очистка сырого migration_sql: чинит типы, дубли, безымянные CONSTRAINT,
 * снимает NOT NULL без DEFAULT у ADD COLUMN, кавычки reserved, дописывает FK из schemaDiff,
 * выкидывает INSERT…SELECT с несуществующими колонками, FK/INDEX → шаг 5.
 */
function cleanupMigrationSql(sql, opts) {
  if (!sql) return sql;
  let text = String(sql);
  const oldTables = parseDdlTables((opts && opts.oldSchema) || "");
  const newTables = parseDdlTables((opts && opts.newSchema) || "");

  // 1) Починить обрезанные DECIMAL/NUMERIC(n
  text = text.replace(/\b(DECIMAL|NUMERIC)\s*\(\s*(\d+)\s+(NOT\s+NULL|NULL|DEFAULT)/gi, "$1($2, 2) $3");
  text = text.replace(/\b(DECIMAL|NUMERIC)\s*\(\s*(\d+)\s*;/gi, "$1($2, 2);");

  // 2) ADD CONSTRAINT FOREIGN KEY → ADD CONSTRAINT fk_… FOREIGN KEY
  text = text.replace(
    /ALTER\s+TABLE\s+([^\s;]+)\s+ADD\s+CONSTRAINT\s+FOREIGN\s+KEY\s*\(\s*([^)]+?)\s*\)\s*REFERENCES\s+([^\s(;]+)\s*(?:\(([^)]*)\))?([^;]*);/gi,
    (_, table, cols, parent, pcol, rest) => {
      const t = normIdent(table);
      const c = normIdent(String(cols).split(",")[0]);
      const pname = `fk_${t}_${c}`.replace(/[^a-z0-9_]/gi, "_").slice(0, 60);
      const pref = pcol ? `(${pcol})` : "(id)";
      return `ALTER TABLE ${table} ADD CONSTRAINT ${pname} FOREIGN KEY (${cols}) REFERENCES ${parent}${pref}${rest || ""};`;
    }
  );

  // 3) Разбить на statements и вычистить дубли / опасный NOT NULL
  const parts = [];
  let buf = "";
  let inS = false, inD = false, inLine = false, inBlock = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i], n = text[i + 1];
    if (inLine) { buf += c; if (c === "\n") inLine = false; continue; }
    if (inBlock) { buf += c; if (c === "*" && n === "/") { buf += "/"; i++; inBlock = false; } continue; }
    if (inS) { buf += c; if (c === "'" && n === "'") { buf += "'"; i++; } else if (c === "'") inS = false; continue; }
    if (inD) { buf += c; if (c === '"') inD = false; continue; }
    if (c === "-" && n === "-") { buf += c; inLine = true; continue; }
    if (c === "/" && n === "*") { buf += c; inBlock = true; continue; }
    if (c === "'") { inS = true; buf += c; continue; }
    if (c === '"') { inD = true; buf += c; continue; }
    if (c === ";") { parts.push(buf.trim()); buf = ""; continue; }
    buf += c;
  }
  if (buf.trim()) parts.push(buf.trim());

  const createFkKeys = new Set();
  const createTables = new Set();
  const createFkCols = []; // { table, col } из CREATE TABLE — для индексов
  const preferredSpell = new Map(); // lower -> as written in script ("Card" or card)
  const rememberSpell = (tok) => {
    const n = normIdent(tok);
    if (!n) return;
    if (/^["`]/.test(tok) || /[A-Z]/.test(String(tok).replace(/^["'`]+|["'`]+$/g, ""))) {
      preferredSpell.set(n, `"${String(tok).replace(/^["'`]+|["'`]+$/g, "")}"`);
    } else if (!preferredSpell.has(n)) {
      preferredSpell.set(n, PG_RESERVED.has(n) ? `"${n}"` : n);
    }
  };
  const spell = (name) => preferredSpell.get(normIdent(name)) || quoteIdentIfNeeded(name);

  parts.forEach(p => {
    const cm = p.match(/CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?(?:"([^"]+)"|(\w+))/i);
    if (cm) {
      const raw = cm[1] || cm[2];
      createTables.add(raw.toLowerCase());
      rememberSpell(cm[1] ? `"${cm[1]}"` : cm[2]);
      const body = p.match(/\(([\s\S]*)\)\s*$/);
      if (body) {
        const re = /(?:FOREIGN\s+KEY\s*\(\s*["'`]?(\w+)["'`]?\s*\)\s*)?REFERENCES\s+["'`]?(\w+)["'`]/gi;
        let r;
        while ((r = re.exec(body[1]))) {
          const col = r[1] || (body[1].slice(Math.max(0, r.index - 80), r.index).match(/["'`]?(\w+)["'`]?\s+[\w().,\s]+$/i) || [])[1];
          createFkKeys.add(raw.toLowerCase() + ">" + (col || "").toLowerCase() + ">" + r[2].toLowerCase());
          createFkKeys.add(raw.toLowerCase() + ">>" + r[2].toLowerCase());
          if (col) createFkCols.push({ table: raw.toLowerCase(), col: col.toLowerCase() });
          rememberSpell(r[2]);
        }
      }
    }
    const am = p.match(/ALTER\s+TABLE\s+("[^"]+"|\w+)/i);
    if (am) rememberSpell(am[1]);
  });

  const seenAlterCol = new Set();
  const seenFkAlter = new Set();
  const out = [];

  for (let p of parts) {
    // убрать внутренние пометки генератора
    p = p.replace(/\s*--\s*причина:[^\n]*/gi, "");
    p = p.replace(/\s*--\s*новое поле[^\n]*/gi, "");
    p = p.replace(/\s*--\s*FK\s*$/gim, "");

    // комментарии перед statement (ШАГ N:) — иначе ^ALTER не матчится
    const leadComments = (p.match(/^((?:\s*--[^\n]*\n)+)/) || [])[1] || "";
    const stmt = p.slice(leadComments.length).trim();
    const keepLead = leadComments.trim() ? leadComments.trim() + "\n" : "";

    // INSERT…SELECT с колонками, которых нет у источника в OLD_SCHEMA — выкинуть
    if (/^INSERT\s+INTO\b/i.test(stmt)) {
      const v = validateInsertSelectAgainstSchema(stmt, oldTables, newTables);
      if (v.skipped) {
        out.push(
          `${keepLead}-- пропущено: INSERT FROM "${v.from}" — нет колонок: ${(v.missing || []).join(", ")} (нет в схеме источника)`.trim()
        );
        continue;
      }
    }

    const alterCol = stmt.match(/^ALTER\s+TABLE\s+("[^"]+"|[^\s]+)\s+ADD\s+COLUMN\s+["'`]?(\w+)["'`]?\s+(.+)$/i);
    if (alterCol) {
      let tableTok = alterCol[1];
      const col = alterCol[2].toLowerCase();
      let rest = alterCol[3].trim().replace(/;?\s*$/, "");
      const tNorm = normIdent(tableTok);
      const key = tNorm + "." + col;
      if (seenAlterCol.has(key)) continue;
      seenAlterCol.add(key);

      rememberSpell(tableTok);
      tableTok = spell(tableTok);

      rest = rest.replace(/^(DECIMAL|NUMERIC)\s*\(\s*(\d+)\s*(?=\s+NOT\s+NULL|\s+NULL|\s+DEFAULT|$)/i, "$1($2, 2)");

      // ADD COLUMN + NOT NULL без DEFAULT — риск падения на данных в существующей таблице.
      // Оставляем nullable; NOT NULL/DEFAULT — после backfill (шаг 2).
      if (/\bNOT\s+NULL\b/i.test(rest) && !/\bDEFAULT\b/i.test(rest)) {
        rest = rest.replace(/\bNOT\s+NULL\b/gi, "").replace(/\s{2,}/g, " ").trim();
      }

      out.push(`${keepLead}ALTER TABLE ${tableTok} ADD COLUMN ${col} ${rest}`.trim());
      continue;
    }

    const alterFk = stmt.match(/^ALTER\s+TABLE\s+("[^"]+"|[^\s]+)\s+ADD\s+CONSTRAINT\s+(\w+)\s+FOREIGN\s+KEY\s*\(\s*([^)]+)\)\s*REFERENCES\s+("[^"]+"|[^\s(;]+)(?:\(([^)]*)\))?(.*)$/i);
    const alterFkAnon = stmt.match(/^ALTER\s+TABLE\s+("[^"]+"|[^\s]+)\s+ADD\s+(?:CONSTRAINT\s+)?FOREIGN\s+KEY/i);
    if (alterFk || alterFkAnon) {
      const tableTok = alterFk ? alterFk[1] : (stmt.match(/ALTER\s+TABLE\s+("[^"]+"|[^\s]+)/i) || [])[1];
      const tNorm = normIdent(tableTok);
      const cols = alterFk ? alterFk[3] : ((stmt.match(/FOREIGN\s+KEY\s*\(\s*([^)]+)\)/i) || [])[1] || "");
      const parent = alterFk ? alterFk[4] : ((stmt.match(/REFERENCES\s+("[^"]+"|[^\s(;]+)/i) || [])[1] || "");
      const col0 = normIdent(String(cols).split(",")[0]);
      const pNorm = normIdent(parent);
      const fkKey = tNorm + ">" + col0 + ">" + pNorm;
      const onDel = ((alterFk && alterFk[6]) || stmt).match(/ON\s+DELETE\s+(CASCADE|RESTRICT|SET\s+NULL|SET\s+DEFAULT|NO\s+ACTION)/i);
      const onDelSql = onDel ? ` ON DELETE ${onDel[1].replace(/\s+/g, " ").toUpperCase()}` : "";

      if (createTables.has(tNorm) && (createFkKeys.has(fkKey) || createFkKeys.has(tNorm + ">>" + pNorm))) continue;
      if (seenFkAlter.has(fkKey)) continue;
      seenFkAlter.add(fkKey);

      const cname = (alterFk && alterFk[2] && !/^foreign$/i.test(alterFk[2]))
        ? alterFk[2]
        : `fk_${tNorm}_${col0}`.replace(/[^a-z0-9_]/gi, "_").slice(0, 60);
      const pcol = (alterFk && alterFk[5]) ? `(${alterFk[5]})` : "(id)";
      // FK на существующих таблицах — уедут в ШАГ 5 через relocateFksAndIndexesToStep5
      out.push(
        `ALTER TABLE ${spell(tableTok)} ADD CONSTRAINT ${cname} FOREIGN KEY (${cols}) REFERENCES ${spell(parent)}${pcol}${onDelSql}`
      );
      continue;
    }

    out.push(p.replace(/;?\s*$/, ""));
  }

  // FK из diff для существующих таблиц (новые колонки с REFERENCES), если модель их забыла
  const diff = (opts && opts.schemaDiff) || {};
  const addedFks = [...(diff.addedFks || [])];
  // Страховка: ALTER ADD COLUMN account_id при наличии таблицы account — даже если NEW DDL без REFERENCES
  const knownTables = new Set([
    ...[...(opts && opts.oldTableNames ? opts.oldTableNames : [])].map(normIdent),
    ...preferredSpell.keys(),
    ...createTables,
  ]);
  createFkKeys.forEach(k => {
    const partsK = String(k).split(">");
    if (partsK[2]) knownTables.add(partsK[2]);
  });
  seenAlterCol.forEach(key => {
    const [t, col] = String(key).split(".");
    const parent = inferParentTableFromCol(col, knownTables);
    if (!parent || parent === t) return;
    if (addedFks.some(f => normIdent(f.child) === t && normIdent(f.col) === col)) return;
    let onDelete = "NO ACTION";
    for (const f of addedFks) {
      if (normIdent(f.parent) === parent && f.onDelete && f.onDelete !== "NO ACTION") {
        onDelete = f.onDelete;
        break;
      }
    }
    // CASCADE с соседних CREATE FK на того же родителя
    if (onDelete === "NO ACTION") {
      const hit = [...createFkKeys].find(k => k.endsWith(">" + parent) && k.includes(">"));
      if (hit) {
        // onDelete возьмём из текста CREATE, если есть
        const re = new RegExp(`REFERENCES\\s+["'\`]?${parent}["'\`]?[^;]*ON\\s+DELETE\\s+(CASCADE|RESTRICT|SET\\s+NULL)`, "i");
        const m = text.match(re);
        if (m) onDelete = m[1].replace(/\s+/g, " ").toUpperCase();
      }
    }
    addedFks.push({ child: t, col, parent, parentCol: "id", onDelete, inferred: true });
  });

  const fkInjects = [];
  addedFks.forEach(f => {
    const tNorm = normIdent(f.child);
    const pNorm = normIdent(f.parent);
    const col = normIdent(f.col);
    if (createTables.has(tNorm)) return; // FK должен быть в CREATE
    const fkKey = tNorm + ">" + col + ">" + pNorm;
    if (seenFkAlter.has(fkKey)) return;
    if (createFkKeys.has(fkKey)) return;
    seenFkAlter.add(fkKey);
    const onDel = f.onDelete && f.onDelete !== "NO ACTION" ? ` ON DELETE ${f.onDelete}` : "";
    const cname = `fk_${tNorm}_${col}`.replace(/[^a-z0-9_]/gi, "_").slice(0, 60);
    fkInjects.push(
      `ALTER TABLE ${spell(f.child)} ADD CONSTRAINT ${cname} FOREIGN KEY (${col}) REFERENCES ${spell(f.parent)}(${f.parentCol || "id"})${onDel}`
    );
  });
  if (fkInjects.length) {
    // до любого фрагмента с COMMIT/ROLLBACK (даже если перед ним комментарии шагов)
    let insertAt = out.findIndex(s => /\b(COMMIT|ROLLBACK)\b/i.test(String(s)));
    if (insertAt < 0) insertAt = out.length;
    const step5 = out.findIndex(s => /--\s*ШАГ\s*5:/i.test(s));
    if (step5 >= 0 && step5 < insertAt) insertAt = step5 + 1;
    out.splice(insertAt, 0, ...fkInjects);
  }

  // Индексы на FK-колонки (CREATE TABLE + ALTER): без CONCURRENTLY — скрипт в транзакции.
  // Составные FK пока пропускаем; дубли по колонкам (не по имени) не плодим.
  const indexCovered = new Set(); // table.col
  const collectIndexCols = (sqlChunk) => {
    const re = /CREATE\s+(?:UNIQUE\s+)?INDEX\s+(?:IF\s+NOT\s+EXISTS\s+)?(?:["'`]?\w+["'`]?\s+)?ON\s+("[^"]+"|\w+)\s*\(\s*([^)]+)\)/gi;
    let m;
    while ((m = re.exec(sqlChunk || ""))) {
      const t = normIdent(m[1]);
      const cols = String(m[2]).split(",").map(c => normIdent(c)).filter(Boolean);
      if (cols[0]) indexCovered.add(t + "." + cols[0]);
    }
  };
  out.forEach(collectIndexCols);
  collectIndexCols(text);

  const fkIndexTargets = [];
  const rememberFkCol = (table, colRaw) => {
    const cols = String(colRaw || "").split(",").map(c => normIdent(c)).filter(Boolean);
    if (cols.length !== 1) return;
    const t = normIdent(table);
    const col = cols[0];
    if (!t || !col) return;
    const key = t + "." + col;
    if (indexCovered.has(key)) return;
    if (fkIndexTargets.some(x => x.table === t && x.col === col)) return;
    fkIndexTargets.push({ table: t, col });
  };

  createFkCols.forEach(f => rememberFkCol(f.table, f.col));
  const alterFkRe = /ALTER\s+TABLE\s+("[^"]+"|\w+)\s+ADD\s+CONSTRAINT\s+\w+\s+FOREIGN\s+KEY\s*\(\s*([^)]+)\)/gi;
  let af;
  const allSqlForFk = out.join("\n");
  while ((af = alterFkRe.exec(allSqlForFk))) rememberFkCol(af[1], af[2]);
  addedFks.forEach(f => rememberFkCol(f.child, f.col));

  const indexInjects = fkIndexTargets.map(({ table, col }) => {
    indexCovered.add(table + "." + col);
    const iname = `idx_${table}_${col}`.replace(/[^a-z0-9_]/gi, "_").slice(0, 60);
    return `CREATE INDEX ${iname} ON ${spell(table)}(${col})`;
  });

  if (indexInjects.length) {
    let insertAt = out.findIndex(s => /\b(COMMIT|ROLLBACK)\b/i.test(String(s)));
    if (insertAt < 0) insertAt = out.length;
    let afterFk = -1;
    for (let i = 0; i < insertAt; i++) {
      if (/ADD\s+CONSTRAINT\s+\w+\s+FOREIGN\s+KEY/i.test(out[i])) afterFk = i + 1;
    }
    if (afterFk >= 0) insertAt = afterFk;
    out.splice(insertAt, 0, ...indexInjects);
  }

  // FK и INDEX всегда в ШАГ 5 (после data/backfill), даже если модель вставила их в ШАГ 2
  const ordered = relocateFksAndIndexesToStep5(out);

  // Собрать обратно, сохранив BEGIN/COMMIT структуру по возможности
  let body = ordered.map(s => /;\s*$/.test(s) ? s : s + ";").join("\n\n");
  if (!/^\s*BEGIN/i.test(body) && /^\s*BEGIN/i.test(text)) body = "BEGIN;\n\n" + body;
  if (!/\bCOMMIT\s*;|\bROLLBACK\s*;/i.test(body) && /\bCOMMIT\s*;/i.test(text)) body += "\n\nCOMMIT;";
  if (!/\bCOMMIT\s*;|\bROLLBACK\s*;/i.test(body) && /\bROLLBACK\s*;/i.test(text)) body += "\n\nROLLBACK;";
  return body.trim() + "\n";
}

function sqlCodeOnly(sql) {
  let code = "";
  mapSqlCodeOnly(sql || "", (c) => { code += c; return c; });
  return code;
}

function lintMigrationSql(sql, dialect) {
  const warnings = [];
  const d = String(dialect || "").toLowerCase();
  const code = sqlCodeOnly(sql);
  if (d === "mysql" || d === "mariadb") {
    if (/\bVARCHAR\s*(?!\s*\()/i.test(code)) warnings.push("MySQL: остался VARCHAR без длины");
  }
  if ((sql.match(/\bSTART\s+TRANSACTION\b|\bBEGIN\b/gi) || []).length && !/\bCOMMIT\b|\bROLLBACK\b/i.test(sql)) {
    warnings.push("Транзакция без COMMIT/ROLLBACK");
  }
  if (/\b(DECIMAL|NUMERIC)\s*\(\s*\d+\s+(NOT\s+NULL|NULL)/i.test(code)) {
    warnings.push("Обнаружен обрезанный DECIMAL/NUMERIC — проверьте типы колонок");
  }
  if (/ADD\s+CONSTRAINT\s+FOREIGN\s+KEY/i.test(code)) {
    warnings.push("ADD CONSTRAINT без имени ограничения");
  }
  return warnings;
}

function buildConstraintFacts(ddl, opts) {
  const compact = !!(opts && opts.compact);
  const tables = parseDdlTables(ddl);
  const lines = [];
  for (const [t, info] of Object.entries(tables)) {
    (info.fks || []).forEach(fk => {
      const action = fk.onDelete || "NO ACTION";
      const expect = action === "CASCADE"
        ? "удаление родителя УСПЕШНО, дочерние строки исчезают; ошибку НЕ ожидать"
        : (action === "SET NULL"
          ? "удаление родителя УСПЕШНО, дочерний FK становится NULL"
          : "удаление родителя должно УПАСТЬ с ошибкой FK (RESTRICT/NO ACTION)");
      lines.push(`FK ${t}.${fk.col} → ${fk.parent}(${fk.parentCol}) ON DELETE ${action} — ${expect}`);
    });
    const nn = [];
    Object.entries(info.cols || {}).forEach(([c, meta]) => {
      if (meta.notNull) nn.push(c);
      if (meta.unique) lines.push(`UNIQUE ${t}.${c} — дубликат должен упасть`);
      if (meta.check) lines.push(`CHECK ${t}.${c}: ${meta.check} — значение вне диапазона должно упасть`);
    });
    if (nn.length) {
      lines.push(compact
        ? `NOT NULL ${t}(${nn.join(", ")}) — достаточно ОДНОГО репрезентативного INSERT NULL, не отдельный тест на каждую колонку`
        : nn.map(c => `NOT NULL ${t}.${c} — INSERT NULL должен упасть`).join("\n"));
    }
    (info.checks || []).forEach(ch => lines.push(`CHECK ${t}: ${ch}`));
    (info.uniques || []).forEach(u => lines.push(`UNIQUE ${t}: ${u}`));
  }
  return lines.filter(Boolean).join("\n") || "(парсер не нашёл FK/CHECK/UNIQUE/NOT NULL — тестируй только то, что явно видно в DDL)";
}

function lintIntegritySql(sql) {
  const warnings = [];
  const text = String(sql || "");
  const blocks = text.split(/BEGIN\s*;/i).slice(1);
  blocks.forEach((block, i) => {
    const n = i + 1;
    const deletes = [...block.matchAll(/DELETE\s+FROM\s+["'`]?(\w+)["'`]?/gi)];
    deletes.forEach(d => {
      const table = d[1];
      const tail = block.slice(d.index || 0);
      const leak = new RegExp(
        "SELECT[\\s\\S]{0,500}?=\\s*\\(\\s*SELECT\\s+[\\w.*]+\\s+FROM\\s+[\"'`]?" + table + "\\b",
        "i"
      );
      if (leak.test(tail)) {
        warnings.push("Блок " + n + ": после DELETE FROM " + table + " проверка ищет строки через подзапрос к уже удалённой таблице. Считайте дочерние записи по их собственному id.");
      }
    });
    const delById = [...block.matchAll(/DELETE\s+FROM\s+["'`]?\w+["'`]?\s+WHERE\s+["'`]?id["'`]?\s*=\s*(\d+)/gi)];
    delById.forEach(d => {
      const parentId = d[1];
      const tail = block.slice(d.index || 0);
      const byFk = new RegExp("SELECT[\\s\\S]{0,400}WHERE\\s+[\"'`]?(?!id\\b)(\\w+)[\"'`]?\\s*=\\s*" + parentId + "\\b", "i");
      const byChildPk = /SELECT\s+COUNT\s*\(\s*\*\s*\)[\s\S]{0,200}WHERE\s+["'`]?id["'`]?\s*=\s*\d+/i.test(tail);
      if (byFk.test(tail) && !byChildPk) {
        warnings.push("Блок " + n + ": CASCADE проверяется по FK = " + parentId + ". Надёжнее COUNT(*) ... WHERE id = <id дочерней строки>.");
      }
    });
    const subParents = [...block.matchAll(/SELECT\s+id\s+FROM\s+["'`]?(\w+)["'`]?\s+WHERE/gi)].map(m => m[1].toLowerCase());
    subParents.forEach(parent => {
      const inserted = new RegExp("INSERT\\s+INTO\\s+[\"'`]?" + parent + "\\b", "i").test(block);
      if (!inserted) {
        warnings.push("Блок " + n + ": подзапрос к " + parent + " без INSERT этой таблицы в том же BEGIN — после ROLLBACK предыдущих тестов строк не будет.");
      }
    });
  });
  return [...new Set(warnings)];
}

const PG_RESERVED_IDENT = /^(user|order|group|table|limit|offset|check|key)$/i;

function quoteReservedTableIdents(sql, dialect) {
  if (!/postgres/i.test(String(dialect || ""))) return sql;
  return String(sql || "").replace(
    /\b((?:INSERT\s+INTO|DELETE\s+FROM|UPDATE|JOIN|FROM|TABLE))\s+(?!["'`])(User|Order|Group|Table|Limit|Offset|Check|Key|user|order|group|table|limit|offset|check|key)\b/g,
    (m, kw, ident) => kw + ' "' + ident + '"'
  );
}

function lintReservedIdents(sql, dialect) {
  if (!/postgres/i.test(String(dialect || ""))) return [];
  const warnings = [];
  const re = /\b(?:INSERT\s+INTO|DELETE\s+FROM|UPDATE|JOIN|FROM|TABLE)\s+(?!["'`])(User|Order|Group|Table|Limit|Offset|Check|Key)\b/gi;
  let m;
  while ((m = re.exec(sql || ""))) {
    warnings.push("Зарезервированное имя " + m[1] + " без кавычек — в PostgreSQL скрипт не выполнится. Нужно \"" + m[1] + "\".");
  }
  return [...new Set(warnings)];
}

function ddlTransactionalNote(dialect) {
  const d = String(dialect || "").toLowerCase();
  if (d === "postgresql" || d === "postgres") return "";
  return "-- ВНИМАНИЕ: в " + d + " DDL (CREATE/ALTER TABLE) обычно делает неявный COMMIT. ROLLBACK не откатит уже выполненные DDL. Не используйте этот скрипт как безопасный dry-run на проде.";
}

module.exports = {
  mysqlVarcharLen,
  sanitizeTargetDialectSql,
  parseDdlTables,
  extractColumnMeta,
  extractTableNames,
  buildSchemaDiff,
  ensureAltersFromDiff,
  ensureFksFromDiff,
  cleanupMigrationSql,
  lintMigrationSql,
  dialectTypeHeader,
  ddlTransactionalNote,
  parseOnDelete,
  buildConstraintFacts,
  lintIntegritySql,
  quoteReservedTableIdents,
  lintReservedIdents,
  validateInsertSelectAgainstSchema,
  relocateFksAndIndexesToStep5,
};
